fix instructions: make curl processing redirects
syncthing/apt-web pull request #32
Opened 2023-11-17 14:20 UTC by nextiny

By default, curl does not follow HTTP redirects, so if there are any, the key will not be added correctly. Adding -L key fixes it.

2023-11-17 14:23 UTC, nextiny commented
`$ curl https://syncthing.net/release-key.txt
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>`

2023-11-18 10:04 UTC, acolomb requested changes

2023-11-18 10:04 UTC, acolomb commented on index.html
> +sudo curl -Lo /etc/apt/keyrings/syncthing-archive-keyring.gpg https://syncthing.net/release-key.gpg</b></pre>
```suggestion
sudo curl -L -o /etc/apt/keyrings/syncthing-archive-keyring.gpg https://syncthing.net/release-key.gpg</b></pre>
```

2023-11-18 10:05 UTC, acolomb approved these changes

2023-11-18 10:06 UTC, merged